Web/Controllers/SearchController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Web.ViewModels;

namespace Web.Controllers
{
  public class SearchController : Controller
  {
    private SupercarModelContext db = new SupercarModelContext();

    //
    // GET: /Search
    [ValidateInput(true)]
    public ActionResult Index(string searchTerm)
    {
      // Reading from query string to demonstrate HTTP verb tampering
      var searchTermQuery = Request.QueryString["searchTerm"];
      if (!string.IsNullOrEmpty(searchTermQuery) && searchTermQuery.Contains("<"))
      {
        return View("IllegalChar");
      }

      var supercars = db.Supercars
                        .Where(s =>
                               s.Make.Name.Contains(searchTerm)
                               || s.Model.Contains(searchTerm)
                               || s.Description.Contains(searchTerm))
                        .Include("Make")
                        .Select(s => new Search
                        {
                          SupercarId = s.SupercarId,
                          Make = s.Make.Name,
                          Model = s.Model,
                          PowerKw = s.PowerKw,
                          TorqueNm = s.TorqueNm,
                          ZeroToOneHundredKmInSecs = s.ZeroToOneHundredKmInSecs,
                          TopSpeedKm = s.TopSpeedKm
                        });

      ViewBag.RawSearchTerm = searchTerm;

      if (!string.IsNullOrEmpty(Request.QueryString["searchTerm"]))
      {
        searchTerm = searchTerm.Replace("<", "").Replace(">", "").Replace("/", "&#47;");
      }

      ViewBag.SearchTerm = searchTerm;
      ViewBag.EncodedSearchTerm = searchTerm;

      return View(supercars);
    }
  }
}

Web/Controllers/SecretController.cs
using System.Linq;
using System.Web.Mvc;

namespace Web.Controllers
{
  public class SecretController : Controller
  {
    private SupercarModelContext db = new SupercarModelContext();

    //
    // GET: /Secret/Admin
    public ActionResult Admin()
    {
      if (User.Identity.IsAuthenticated && db.UserProfiles.Any(u => u.Email == User.Identity.Name && u.IsAdmin != null && u.IsAdmin.Value))
      {
        return View();
      }
      else
      {
        return View("AccessDenied");
      }
    }

    //
    // GET: /Secret/Users
    public ActionResult Users()
    {
        if (User.Identity.IsAuthenticated && db.UserProfiles.Any(u => u.Email == User.Identity.Name && u.IsAdmin != null && u.IsAdmin.Value))
        {
            var users = db.UserProfiles;
            return View(users);
        }
        else
        {
            return View("AccessDenied");
        }
    }
  }
}

Web/Controllers/SupercarController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Web.Mvc;
using Web.Filters;
using Web.Models;
using Web.ViewModels;

namespace Web.Controllers
{
    [InitialiseDatabase]
    public class SupercarController : Controller
    {
        private SupercarModelContext db = new SupercarModelContext();

        public ActionResult Index(int id = 0)
        {
            var supercar = db.Supercars
                             .Include("Make")
                             .Include("Votes")
                             .Include("Votes.User")
                             .SingleOrDefault(s => s.SupercarId == id);

            if (supercar == null)
            {
                return HttpNotFound();
            }

            ViewBag.TotalVotes = (decimal)db.Votes.Count();

            if (User.Identity.IsAuthenticated)
            {
                var profile = db.UserProfiles.SingleOrDefault(u => u.Email == User.Identity.Name);
                if (profile != null)
                {
                    ViewBag.FirstName = profile.FirstName;
                    ViewBag.LastName = profile.LastName;
                }
            }

            return View(supercar);
        }

        public ActionResult Leaderboard(string orderBy = "votes", bool asc = true)
        {
            try
            {
                var supercars = db.Supercars.SqlQuery("SELECT * FROM Supercar").ToList();

                supercars = asc
                    ? supercars.OrderBy(orderBy == "votes" ? "SupercarId" : orderBy).ToList()
                    : supercars.OrderByDescending(orderBy == "votes" ? "SupercarId" : orderBy).ToList();


                if (orderBy == "votes")
                {
                    supercars = supercars.OrderByDescending(s => s.Votes.Count()).ToList();
                }

                var leaderboard = supercars.Select(s => new Leaderboard
                {
                    SupercarId = s.SupercarId,
                    Make = s.Make.Name,
                    Model = s.Model,
                    PowerKw = s.PowerKw,
                    TorqueNm = s.TorqueNm,
                    ZeroToOneHundredKmInSecs = s.ZeroToOneHundredKmInSecs,
                    TopSpeedKm = s.TopSpeedKm,
                    Votes = s.Votes.Count()
                });

                return View(leaderboard);
            }
            catch (SqlException)
            {
                return View("LeaderBoardError");
            }
        }
    }

    public static class LinqExtensions
    {
        private static PropertyInfo GetPropertyInfo(Type objType, string name)
        {
            var properties = objType.GetProperties();
            var matchedProperty = properties.FirstOrDefault(p => p.Name == name);
            if (matchedProperty == null)
                throw new ArgumentException("name");

            return matchedProperty;
        }
        private static LambdaExpression GetOrderExpression(Type objType, PropertyInfo pi)
        {
            var paramExpr = Expression.Parameter(objType);
            var propAccess = Expression.PropertyOrField(paramExpr, pi.Name);
            var expr = Expression.Lambda(propAccess, paramExpr);
            return expr;
        }

        public static IEnumerable<T> OrderBy<T>(this IEnumerable<T> query, string name)
        {
            var propInfo = GetPropertyInfo(typeof(T), name);
            var expr = GetOrderExpression(typeof(T), propInfo);

            var method = typeof(Enumerable).GetMethods().FirstOrDefault(m => m.Name == "OrderBy" && m.GetParameters().Length == 2);
            var genericMethod = method.MakeGenericMethod(typeof(T), propInfo.PropertyType);
            return (IEnumerable<T>)genericMethod.Invoke(null, new object[] { query, expr.Compile() });
        }

        public static IEnumerable<T> OrderByDescending<T>(this IEnumerable<T> query, string name)
        {
            var propInfo = GetPropertyInfo(typeof(T), name);
            var expr = GetOrderExpression(typeof(T), propInfo);

            var method = typeof(Enumerable).GetMethods().FirstOrDefault(m => m.Name == "OrderByDescending" && m.GetParameters().Length == 2);
            var genericMethod = method.MakeGenericMethod(typeof(T), propInfo.PropertyType);
            return (IEnumerable<T>)genericMethod.Invoke(null, new object[] { query, expr.Compile() });
        }

        public static IQueryable<T> OrderBy<T>(this IQueryable<T> query, string name)
        {
            var propInfo = GetPropertyInfo(typeof(T), name);
            var expr = GetOrderExpression(typeof(T), propInfo);

            var method = typeof(Queryable).GetMethods().FirstOrDefault(m => m.Name == "OrderBy" && m.GetParameters().Length == 2);
            var genericMethod = method.MakeGenericMethod(typeof(T), propInfo.PropertyType);
            return (IQueryable<T>)genericMethod.Invoke(null, new object[] { query, expr });
        }
    }
}

Web/Views/Shared/_Layout.cshtml
@using Web
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>@ViewBag.Title - Supercar Showdown</title>
  <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
  <meta name="viewport" content="width=device-width" />
  @Styles.Render("~/Content/site")
  @RenderSection("styles", false)
  @{
    var db = new SupercarModelContext();
    var userProfile = db.UserProfiles.SingleOrDefault(u => u.Email == User.Identity.Name);
  }
</head>
<body>
  <header class="navbar-wrapper">
    <div class="container">
      <div class="navbar navbar-inverse">
        <div class="navbar-inner@{if (Request.Url.Host.StartsWith("secure.")){<text> secure</text>}}">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="@Url.Action("Index", "Home", null, "https")">Supercar Showdown</a>
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li><a href="@Url.Action("Leaderboard", "Supercar", null, "https")">Leaderboard</a></li>
                @if (userProfile != null)
                {
                  <li id="account" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">My account <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <form action="@Url.Action("LogOff", "Account", null, "https")" method="post" class="navbar-form">@Html.AntiForgeryToken()</form>
                      <li><a href="@Url.Action("ChangePassword", "Account", null, "https")">Change password</a></li>
                      <li><a href="@Url.Action("UserProfile", "Account", null, "https")">Edit profile</a></li>
                      <li><a id="logoutForm" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                    </ul>
                  </li>
          
                  if (userProfile.IsAdmin != null && userProfile.IsAdmin.Value)
                  {
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="@Url.Action("Users", "Secret", null, "https")">Manage users</a></li>
                    </ul>
                  </li>
                  }
                }
              </ul>
              <section class="navbar-form pull-right">
                @if (userProfile != null)
                {
                  <ul class="nav">
                    <li><a>Hello @userProfile.FirstName!</a></li>
                  </ul>
                }
                else
                {
                  <ul class="nav">
                    <li>@Html.ActionLink("Register", "Register", "Account")</li>
                    <li>@Html.ActionLink("Log in", "Login", "Account")</li>
                  </ul>
                }
                  <form action="@Url.Action("Index", "Search", null, "https")" method="get" class="navbar-search">
                      @Html.AntiForgeryToken()
                      <input type="text" class="search-query span2" placeholder="Search" name="searchTerm" id="searchTerm"/>
                  </form>
              </section>
            </div>
          </div>
      </div>
    </div>
  </header>
  @RenderSection("featured", false)
  <div class="container">
    <section>
      @RenderBody()
    </section>
    <hr>
    <footer>
      <p>&copy; @DateTime.Now.Year - Hack Yourself First</p>
    </footer>
  </div>
  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/jqueryval")
  @Scripts.Render("~/bundles/bootstrap")
  @RenderSection("scripts", false)
</body>
</html>